/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({
  id: '/conditions-utilisation',
  path: '/conditions-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/cookies': typeof CookiesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/cookies': typeof CookiesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/cookies': typeof CookiesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/conditions-utilisation' | '/cookies' | '/politique-confidentialite'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/conditions-utilisation' | '/cookies' | '/politique-confidentialite'
  id:
    | '__root__'
    | '/'
    | '/conditions-utilisation'
    | '/cookies'
    | '/politique-confidentialite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  CookiesRoute: typeof CookiesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-utilisation': {
      id: '/conditions-utilisation'
      path: '/conditions-utilisation'
      fullPath: '/conditions-utilisation'
      preLoaderRoute: typeof ConditionsUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsUtilisationRoute: ConditionsUtilisationRoute,
  CookiesRoute: CookiesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
